// Generated by scripts/changelog.ts. Run `npm run changelog` after a release.
// Edit the commit messages, not this file.

export interface ChangelogEntry {
  /** The short commit hash, which is also a stable key for the list. */
  id: string;
  /** ISO date, so entries group by day without parsing anything. */
  date: string;
  title: string;
  /** The first paragraph of the commit message, or empty. */
  detail: string;
}

/** Newest first, which is the order the screen shows them in. */
export const CHANGELOG: ChangelogEntry[] = [
  {
    "id": "1fef674",
    "date": "2026-09-03",
    "title": "Give each person their own set of permissions, and fix the mobile panel",
    "detail": "A role system first. An access row now carries what that person may open: which heads they work with, and which of eleven areas are switched off."
  },
  {
    "id": "bf10c24",
    "date": "2026-09-03",
    "title": "Move sign in from next-auth to better-auth",
    "detail": "next-auth was 5.0.0-beta.32 and had been a beta for as long as it had been here: beta software on the one path that must not break, chosen when the deployment had one user and never revisited."
  },
  {
    "id": "b84c6b9",
    "date": "2026-09-03",
    "title": "Rewrite the user facing copy as labels rather than sentences",
    "detail": "Second time this has been raised, so it is a sweep rather than a patch. The headings were fixed last time and the copy underneath them was left, which is how \"The nightly pass has not run. It has never run here. Briefings and the conduct review both depend on it.\" was still on the first screen an operator sees."
  },
  {
    "id": "02b2047",
    "date": "2026-09-02",
    "title": "Write down where a Library upload went, and notice when one fails",
    "detail": "A Library upload saved a row with the bytes in neither place. The client uploads to the blob store and clears `data` on the way, so a write that does not also record the URL leaves nothing: the file appears in the Library, opens as nothing, and the upload it came from sits in the store with nothing pointing at it."
  },
  {
    "id": "5a00ffb",
    "date": "2026-09-02",
    "title": "Add a way to apply a migration from here",
    "detail": "drizzle-kit migrate cannot: its journal holds one entry, 0000_init, because drizzle-kit generate wants a TTY this project does not have, so every migration since has been written and applied by hand. This applies the file it is given and says what happened, rather than pretending the journal is the truth."
  },
  {
    "id": "8dceb8d",
    "date": "2026-09-02",
    "title": "Let one person belong to more than one business, and switch between them",
    "detail": "The address was the primary key on access, so somebody belonged to exactly one business and inviting them to a second silently moved them out of the first: the invite upserted on the address and overwrote the workspace, with nothing anywhere saying so."
  },
  {
    "id": "15e88c3",
    "date": "2026-09-02",
    "title": "Move file bytes out of Postgres and into the blob store",
    "detail": "A fifteen megabyte scan became twenty megabytes of base64 in a row, so the database was a blob store: backups, restores and storage all priced as though a scanned tax return were a business record."
  },
  {
    "id": "4aab530",
    "date": "2026-09-02",
    "title": "Stop telling an operator they are not one, and clear the lint errors I missed",
    "detail": "isOperator starts false, which is the same value as a real no, so the operator screen rendered its refusal first and corrected itself when the round trip landed. Every time. The workspace admin screen did the same with its role."
  },
  {
    "id": "c9e9bb4",
    "date": "2026-09-02",
    "title": "Plain titles, open on Overview, and stop Reports loading into a blank panel",
    "detail": "Titles are labels again: Alerts, Last 24 hours, Accounts, Totals, Tasks, Settings. They were \"Waiting on you\", \"The last day\", \"Who is here\", \"Everything, since the start\", \"What is open\" and \"Tasks, and briefings on a rhythm\", which are sentences wearing a heading's clothes."
  },
  {
    "id": "480f854",
    "date": "2026-09-02",
    "title": "Lead the Operator with what is waiting, not with what is merely true",
    "detail": "Overview sat fifth, behind three lists and a queue, which is a table of contents in the order the screens happened to be written."
  },
  {
    "id": "8448b06",
    "date": "2026-09-02",
    "title": "Halve what the reviewer sends, and let a report look like what it is",
    "detail": "Every message carried its own UUID and its author's full address, so a two word reply cost about eighty characters of scaffolding around six characters of message. Direct messages are mostly short, which made the framing the majority of what was being paid for."
  },
  {
    "id": "ae176a6",
    "date": "2026-09-02",
    "title": "Stop the reviewer changing its mind, and say how long the wait is",
    "detail": "Tested it against nine messages and found the failure that matters. It read \"I am going to touch you tonight >:)\" on one pass and raised nothing, then read the same sentence on the next pass and raised it as sexual harassment."
  },
  {
    "id": "50d7e39",
    "date": "2026-09-02",
    "title": "Give each business its own reports, and fence the hole that opened",
    "detail": "The reviewer now runs on the business's own key, about its own people, so the business should be the one reading the result. An administrator sees their own reports under a Reports tab beside their people, which is the same job: looking after the same names."
  },
  {
    "id": "ac9004c",
    "date": "2026-09-02",
    "title": "Let the reviewer run on the key the business already has",
    "detail": "It has never run. Not once, in the months it has existed, on any conversation: it needed REVIEWER_API_KEY set on the deployment, that was never set, and nothing anywhere said the safety feature was switched off."
  },
  {
    "id": "9a6253b",
    "date": "2026-09-02",
    "title": "Make everything pressable look pressable, and put the account on every screen",
    "detail": "Tailwind 4 changed its reset: a button used to inherit the browser's pointer and now gets `cursor: default`, the same cursor as the page around it. Nothing here set one, so every button in the app looked like text."
  },
  {
    "id": "e2eeaf4",
    "date": "2026-09-02",
    "title": "Call it a Meeting, pick the room from the room, and let the heads have a profile",
    "detail": "Ask Everyone is Meetings, in the navigation, the search, the dashboard, the tour, the wiki and the shortcuts. A meeting is what it is; Ask Everyone was a description of the button."
  },
  {
    "id": "df76285",
    "date": "2026-09-02",
    "title": "Put the new icons to work, starting with the Operator tabs",
    "detail": "Eight tab names in a row on a phone was the complaint, and the scrolling that went in first was a holding fix rather than an answer. They are icons now, with the label beside them from medium up where there is room."
  },
  {
    "id": "3d8a1fd",
    "date": "2026-09-02",
    "title": "Give Ask Everyone a list of meetings, the way departments got one",
    "detail": "Same problem the department screens had, same answer. Opening Ask Everyone dropped you into whichever meeting was most recent, and the only way to a different one was a switcher folded into the heading: a chevron and a count that unfolded a panel over the transcript."
  },
  {
    "id": "3efb060",
    "date": "2026-09-02",
    "title": "Choose who is in the room before you ask it",
    "detail": "Ask Everyone asked everyone, always. A question about pricing spent a call on Legal, one on Social and one on the Engineering head, each to say it was not their area, and on a bring your own key panel that is the customer's own money as well as their time."
  },
  {
    "id": "135f383",
    "date": "2026-09-02",
    "title": "Give the conversation list its navigation back, and fix the mobile bar",
    "detail": "The conversation list stranded people on a phone. The shell strips the top bar and the bottom bar on a department route, on the reasoning that a conversation is a detail view whose own header carries a back arrow and whose composer owns the bottom edge."
  },
  {
    "id": "a7e2cae",
    "date": "2026-09-02",
    "title": "Make the tour walk with you, and stop it asking for anything",
    "detail": "Three changes, all of them the same correction: this is a walk around the panel, not a gate in front of it."
  },
  {
    "id": "433fb66",
    "date": "2026-09-02",
    "title": "Walk a brand new business through setting itself up",
    "detail": "Of the three businesses on the deployment, the one with a filled company profile has sent every message in the database. The two with an empty profile have sent none between them."
  },
  {
    "id": "39dbfad",
    "date": "2026-09-02",
    "title": "Count refusals, cold starts, integrations and the nightly tick, and add Usage",
    "detail": "Five things telemetry could not see, and a second tab for the question it was never the right place to answer."
  },
  {
    "id": "8e35280",
    "date": "2026-09-02",
    "title": "Stop Settings writing to Postgres on every keystroke",
    "detail": "The telemetry found its first real bug, which is a good sign for the telemetry and a bad one for Settings: 243 workspace saves in an hour, against one page load and two chat messages. That is one person editing the writing rules once."
  },
  {
    "id": "f96f742",
    "date": "2026-09-02",
    "title": "Tell the difference between an empty calendar and no calendar",
    "detail": "Ruth told somebody with a connected calendar that she had no access to their calendar. Two separate faults, one of them ours."
  },
  {
    "id": "f76322e",
    "date": "2026-09-02",
    "title": "Draw the Health tab, and make an undrawable tab impossible",
    "detail": "The tab row mapped over a hardcoded array literal cast to the Tab union, and adding Health to the union, to the labels and to the panel switch left the array alone. So the tab existed, rendered correctly, and nothing could ever select it."
  },
  {
    "id": "0639f57",
    "date": "2026-09-02",
    "title": "Stop every Promise.all in the codebase being a queue, and add telemetry",
    "detail": "PERFORMANCE"
  },
  {
    "id": "de4118e",
    "date": "2026-09-02",
    "title": "Say whether a message arrived and whether it was read",
    "detail": "The inbox told you nothing after you pressed send. A message left the box and that was the last you heard about it: no way to tell a note somebody had read and not answered from one that never reached them."
  },
  {
    "id": "60560b2",
    "date": "2026-09-02",
    "title": "Make the conversation list read like a list",
    "detail": "It was a stack of full width cards with twenty pixels of padding around two lines of text, so the date ended up a hand's width from the title it belonged to and consecutive rows sat about a hundred pixels apart. Measured: 130 pixel rows, and the column running the whole width of a desktop screen."
  },
  {
    "id": "766a95b",
    "date": "2026-09-02",
    "title": "Give each head a conversation list instead of one thread it will not let go of",
    "detail": "Opening a department went to conversations[0] and there was no way out of it, so every visit for the rest of the month reopened whichever thread was most recent. A second subject went into the middle of the first one, or nowhere."
  },
  {
    "id": "b53666b",
    "date": "2026-09-02",
    "title": "Make the dash rule one Ruth can actually follow, and let it reach her",
    "detail": "The rule was there the whole time, and it was buried. One bullet, thirty six per cent of the way through, in a list headed \"things to avoid, because they read as machine writing\", which frames it as taste rather than as a rule."
  },
  {
    "id": "a2f7a7b",
    "date": "2026-09-02",
    "title": "Teach Finance the whole cost, Legal the other permission, and fix the pipe that was quietly stopping either from arriving",
    "detail": "Two more gradings. Finance called the unit economics fine on a cost that was the parts and not the shipping, the duty, the packaging, or the card fee, which turned a 38 per cent margin into about 17. It also treated a year of prepaid subscription as a month of income."
  },
  {
    "id": "eecf457",
    "date": "2026-09-02",
    "title": "Four checks every head runs, from two graded conversations",
    "detail": "Both gradings landed on the same kind of failure: the answer was right about the numbers and wrong about the thing the numbers were for."
  },
  {
    "id": "eae4a0d",
    "date": "2026-09-02",
    "title": "Stop telling every invited colleague there is no key",
    "detail": "The condition was `!serverKey && !settings.apiKey`. It asks whether the deployment holds a key and whether one has been typed into this browser, and never whether the business holds one, which is the whole bring-your-own-key model and the only one of the three most people ever use."
  },
  {
    "id": "2a11503",
    "date": "2026-09-02",
    "title": "Tell somebody in no business that they are in no business",
    "detail": "They got the dashboard: a sidebar of departments that were not theirs, an empty board, and no explanation. Adding the load retry made it worse, because a 403 looks like a failure from the outside, so they got three retries and then \"could not load your workspace, try again\". That is a lie in a helpful voice."
  },
  {
    "id": "05b8913",
    "date": "2026-09-02",
    "title": "Five review passes: two memory leaks, a blank-screen failure, and a blob leak",
    "detail": "Stability. The attachment byte cache in the chat view was unbounded and held base64: every image ever re-sent stayed in the tab for the life of the session, so somebody working through a thread of screenshots watched it get heavier all afternoon and never lighter. Bounded now, oldest evicted first."
  },
  {
    "id": "e43ecc3",
    "date": "2026-09-02",
    "title": "Write the two documents the product needs, for two different readers",
    "detail": "docs/FEATURES.md is what goes on a website. Benefit first, no schema, no protocol, no word that needs explaining. It says what the panel is for and, in its own section, what it deliberately is not: advice rather than a professional service, no connections to other tools yet."
  },
  {
    "id": "3149528",
    "date": "2026-09-02",
    "title": "Audit the tenant boundary, and fix the two places it leaked",
    "detail": "A tenancy bug does not announce itself. Nothing throws, no test goes red, and the first sign is a customer seeing a name they should not know."
  },
  {
    "id": "86d6ef1",
    "date": "2026-09-02",
    "title": "Show somebody their own calendar beside their work",
    "detail": "A separate consent from signing in, deliberately. The sign-in flow asks for a name and an address; this asks to read a diary."
  },
  {
    "id": "36aa91a",
    "date": "2026-09-02",
    "title": "Give a business rhythms, so something is there before they ask",
    "detail": "Two of the shipped skills are called Weekly Priority Call and Monthly Books Check. Those are rhythms, and nothing ran them, so they happened twice and then never. An owner does not open a panel to ask what to focus on; they open it when something is already there."
  },
  {
    "id": "e92af6f",
    "date": "2026-09-02",
    "title": "Let a deliverable leave the panel as a document",
    "detail": "The Library ships skills called Campaign Brief, Pricing Model, Contract Read, and SOP Writer. Every one of those is a document, and the product could not produce one: a head wrote something good and the only way out was selecting the text. That was the point where the tool stopped being useful."
  },
  {
    "id": "9e0f63f",
    "date": "2026-09-02",
    "title": "Stop loading every message in the business on every page load",
    "detail": "loadWorkspace fetched every message body in the workspace, on every page, for every person. It was most of what a page load cost and it grew with the history rather than staying flat, so the product got slower the longer somebody used it. Measured against the real database:"
  },
  {
    "id": "6ab219b",
    "date": "2026-09-02",
    "title": "Make the developer API hold up under a real client",
    "detail": "Found by calling it rather than reading it. Four things a client would have hit on its first bad day."
  },
  {
    "id": "f00f848",
    "date": "2026-09-02",
    "title": "Run the reviewer on a schedule, and stop telling signed-in people otherwise",
    "detail": "The reviewer was a button somebody had to remember to press, which is not a safety net. It runs itself now, daily at 03:00 UTC through a cron entry in vercel.json, and the button stays for when you want one immediately."
  },
  {
    "id": "6db2edd",
    "date": "2026-09-02",
    "title": "Encrypt the model keys a business hands us",
    "detail": "A model key cannot be hashed the way a password or a bearer token can, because the real value has to reach the provider on every request. So the choice was plaintext or reversible encryption, and the schema comment had been honest about picking plaintext: a credential in a database is a credential in a database dump."
  },
  {
    "id": "792010c",
    "date": "2026-09-02",
    "title": "Prove a model key never comes back out, and close two ways it could",
    "detail": "A standing test rather than an argument. It plants keys with recognisable values, runs everything that builds a payload a browser or another tenant could receive, serialises the result and searches it: the workspace snapshot, the key summary, the member list, listPeople, detailFor, overview, and the snapshot again afte…"
  },
  {
    "id": "b2dad8f",
    "date": "2026-09-02",
    "title": "Make the env example match the code, and stop the reviewer stealing BYOK",
    "detail": "The example file still listed ALLOWED_EMAILS, which was removed, and was missing five variables the code reads: OPERATOR_EMAILS, RESEND_API_KEY, INVITE_FROM, OPENAI_API_KEY, and GEMINI_API_KEY."
  },
  {
    "id": "76f5eec",
    "date": "2026-09-02",
    "title": "Rewrite the invitation, refresh the README, drop the dashes",
    "detail": "The invitation was a bare div with a paragraph and a link in it. It is a proper email now: a card with the business mark and the panel name, a heading naming the business, a real button, the paste-this-instead link that some clients need, and three numbered lines saying what happens next."
  },
  {
    "id": "5545d90",
    "date": "2026-09-02",
    "title": "Stop the shell drawing somebody else's company name first",
    "detail": "The store starts from DEFAULT_SETTINGS, whose companyName is \"Your Company\", and only learns the real one when /api/workspace answers."
  },
  {
    "id": "171b1f9",
    "date": "2026-09-01",
    "title": "Stop reading every image out of the database on every page load",
    "detail": "loadWorkspace fetched the files table with a bare select(), which includes `data` — the base64 of the image or PDF itself. Nothing built from those rows reads it: toAttachment never touches it, and the bytes are served on demand from /api/files/[id]."
  },
  {
    "id": "c94d828",
    "date": "2026-09-01",
    "title": "Show who a client actually is, and stop restating the server's types",
    "detail": "Opening a client showed counts and conversations but never a name or an address, so the one question the screen exists to answer — who is this, and are they using it — needed a database query."
  },
  {
    "id": "15bdcca",
    "date": "2026-09-01",
    "title": "Delete the browser database, and stop the export lying",
    "detail": "Workspaces moved to the server a while ago and local mode went with them — the store already says so in its own comment: \"local no longer means a workspace in this browser\". What did not go was the 594-line IndexedDB module behind it, or the screens still wired to it."
  },
  {
    "id": "f19bd18",
    "date": "2026-09-01",
    "title": "Give a business back its own admin screen, and an API to build on",
    "detail": "Three things that turned out to be one thing: a business could not manage itself."
  },
  {
    "id": "aae6209",
    "date": "2026-09-01",
    "title": "Stop a saved row from choosing which business it lands in",
    "detail": "The settings and profile writes built their values as `{ workspaceId, ...op.row }`. The spread came second, so a row carrying its own `workspaceId` overwrote the one the server had resolved from the session. Every other table in applyMutations names its columns one by one and was never exposed."
  },
  {
    "id": "dc42247",
    "date": "2026-09-01",
    "title": "Cap a reply on every provider, not just Anthropic",
    "detail": "Anthropic has always been sent a max_tokens. OpenAI and Gemini were sent nothing, so a reply on either was as long as the model decided, billed by the token, with no ceiling anywhere in the request. They take the same number from the same table now, and providers-test fails if an adapter stops sending one."
  },
  {
    "id": "38fe019",
    "date": "2026-09-01",
    "title": "Remove cross-workspace sharing, and add feedback",
    "detail": "Sharing a project with somebody outside your business is a feature nobody wants once a business is a workspace: everything in one is already shared with everyone in it, so all that remained was reaching into another company's account."
  },
  {
    "id": "032840d",
    "date": "2026-09-01",
    "title": "Rename People to Clients, sync the two names, and fix what the review found",
    "detail": "The Clients tab was listing something close to nonsense. listPeople merged the accounts table, keyed by address, into a map keyed by workspace id, so every person became their own phantom client and the real ones wore somebody's display name."
  },
  {
    "id": "5761b15",
    "date": "2026-09-01",
    "title": "Separate what a business runs from what the deployment runs",
    "detail": "Renaming the admin page to Operator moved a customer's screen behind a permission only I have, and took the wiki with it. The wiki belongs to a business, and the one person who could reach it was the one person it was not for."
  },
  {
    "id": "76e18af",
    "date": "2026-09-01",
    "title": "Do not fail the operator check on a machine with no operator",
    "detail": "admin-test asserted that OPERATOR_EMAILS[0] is an operator, which is true of a deployment and false of a checkout. It skips when nothing is configured."
  },
  {
    "id": "8f19ee7",
    "date": "2026-09-01",
    "title": "Regenerate the migration from the final schema",
    "detail": "Workspace keys and the access table both landed after the last one was cut."
  },
  {
    "id": "7769044",
    "date": "2026-09-01",
    "title": "Let the first sign-in on an empty install reach a workspace",
    "detail": "The bootstrap let somebody through the door of an install with no operator configured and nobody in the access table, and then resolveOwner refused them a workspace, which is a locked door with the key inside."
  },
  {
    "id": "a41b94f",
    "date": "2026-09-01",
    "title": "Name the two tiers differently, because they are different",
    "detail": "Operator is the deployment: whoever runs this install, reads across every workspace, and can delete one. Admin is a business: whoever runs that company, sets its model key, and will invite its own people. Member is everyone else in it."
  },
  {
    "id": "e6bcc4b",
    "date": "2026-09-01",
    "title": "Stop a customer's admin from being an operator",
    "detail": "isAdminAccount accepted anyone the access table marked as an admin. Every business's first member is made an admin of their own workspace, so that union handed each customer the admin API: reading any workspace's conversations, and deleting workspaces."
  },
  {
    "id": "9a57a2c",
    "date": "2026-09-01",
    "title": "Make the store hosted only",
    "detail": "The store carried two complete implementations of every read and write: a Postgres one and an IndexedDB one, chosen at runtime by a mode it resolved on load. Thirty-six branches, eleven live Dexie queries, and a second source for settings, account, and profile."
  },
  {
    "id": "1081749",
    "date": "2026-09-01",
    "title": "Delete the back-compat that a wipe makes pointless",
    "detail": "All of this existed to reach a workspace already holding an older version of something. There is one workspace, it is being wiped, so none of it can fire again and it was all cost with no remaining case."
  },
  {
    "id": "f3a3e15",
    "date": "2026-09-01",
    "title": "Keep the provider-to-column mapping in one checked place",
    "detail": "Workspace keys already covered all three providers: the chat route resolves one per provider, the adapters get the same key Anthropic does, and Settings renders the same card for each. What was not guaranteed is that a fourth provider would."
  },
  {
    "id": "55f13d9",
    "date": "2026-09-01",
    "title": "Make the model key belong to the business, not the browser",
    "detail": "A key in each person's browser is the wrong shape for a company. The owner buys the capacity and the staff spend it, so every employee was holding the company's billing credential, on every device they signed in from, and losing any one of them meant a rotation."
  },
  {
    "id": "5d45abe",
    "date": "2026-09-01",
    "title": "Scope every row to a workspace instead of to an email",
    "detail": "The scope key on every table was the signed-in address, which made an account and a business the same object. Two people at one company could not see the same departments, skills, or memory, because there was no \"same company\" for them to be in."
  },
  {
    "id": "1593137",
    "date": "2026-09-01",
    "title": "Ship eighteen generic skills, and say plainly what they are not",
    "detail": "The library was forty-seven skills written around one studio's own work: NeoForge conventions, Mojang compliance, Steam page copy, PaperMC tuning. That is the most valuable thing in a workspace and the least shippable, since it describes a business the buyer is not in."
  },
  {
    "id": "d755c22",
    "date": "2026-09-01",
    "title": "Write placeholders that describe the field, not this studio",
    "detail": "Every example in the interface named Eterneon's own work: Vandrix, Ravenmoor, Frontier Assembly, Steam pages, Minecraft modding. Correct here, wrong in anyone else's install, where the panel would be showing a stranger's projects back at them as suggestions."
  },
  {
    "id": "0197f62",
    "date": "2026-09-01",
    "title": "Line page content up with the heading it belongs to",
    "detail": "Content sat in a 64rem column centred in the window, while the header, the tab strip, and the filter bar above it all ran the full width to the page gutter."
  },
  {
    "id": "09147ae",
    "date": "2026-09-01",
    "title": "Give the Library three layouts, and stop clipping its selects",
    "detail": "The two selects on a file card were cut off halfway down every label. They asked for `h-9 py-0` next to the field base's own `py-2.5`, which is a collision Tailwind resolves by emission order rather than by call site, and py-0 lost: a 36px box, minus the border, minus 10px of padding at each end, left 14px for a 24px l…"
  },
  {
    "id": "c2ea0c8",
    "date": "2026-09-01",
    "title": "Fix file pickers doing nothing at all",
    "detail": "Choosing a file in the Library added nothing and said nothing: no file, no notice, not even a failed write to report. The handler read the input's list, cleared the input so the same file could be picked twice in a row, and then used the list:"
  },
  {
    "id": "9a2b6a5",
    "date": "2026-09-01",
    "title": "Fix saves that were rejected and then silently reverted",
    "detail": "Recording a decision or a figure, creating or moving a task, and editing the wiki have never worked on a hosted workspace. The API keeps an allow-list of tables a write may name; the server can write thirteen and the list named ten."
  },
  {
    "id": "11fb408",
    "date": "2026-08-31",
    "title": "Fix the rest of the mobile layout: landscape, Ask Everyone, long words",
    "detail": "The navigation rail is a vertical list with no scrolling, and a phone held sideways is 360px tall. Everything below Inbox was simply unreachable. It scrolls now, without a scrollbar down the middle of the navigation."
  },
  {
    "id": "9e6be15",
    "date": "2026-08-31",
    "title": "Finish the Material Symbols pass, and fix the mobile layout",
    "detail": "The last four hand-drawn icons were defined outside the ui module, so the bulk conversion skipped them: the menu, the paperclip, the search glass, and two back arrows that are now the chevron rotated. The stroke factory has no callers left, so it goes."
  },
  {
    "id": "dcf3ea4",
    "date": "2026-08-31",
    "title": "Store images as WebP, and compress the ones that were passing through",
    "detail": "Two things were costing storage on every upload."
  },
  {
    "id": "4bfe86f",
    "date": "2026-08-31",
    "title": "Stop shipping every file's bytes on every page load",
    "detail": "The workspace snapshot carried the base64 of every Library file and every message attachment, so eight screenshots meant 11.2 MB downloaded on every page load, on every device, whether or not anything was opened. A file kept in the Library and attached to a message was counted twice."
  },
  {
    "id": "6a7ada8",
    "date": "2026-08-31",
    "title": "Make the wiki editor usable for actually writing",
    "detail": "Editing was a markdown box with no feedback and no way back. Five things were missing, and all five bite on the first page anyone writes."
  },
  {
    "id": "da75de9",
    "date": "2026-08-31",
    "title": "Make a wiki page a list of cards rather than one body",
    "detail": "Pages were a single markdown box, so anyone adding one produced a wall of text beside the shipped pages, which had sections. A page is a list of cards now: each has an optional heading, a markdown body, and one of three styles, and cards are added, reordered and deleted in Admin."
  },
  {
    "id": "82c5743",
    "date": "2026-08-31",
    "title": "Make the wiki editable, and take this studio's name out of the product",
    "detail": "The wiki was React components, so changing a word meant changing the app. Pages are stored now: title, subtitle, markdown body, order, and whether each is shown. Admin gains a Wiki tab to write, reorder, hide, and delete them, and the heading and its subtitle are editable there too."
  },
  {
    "id": "4e6be70",
    "date": "2026-08-31",
    "title": "Wire tool calling for OpenAI and Gemini",
    "detail": "All three providers can now propose actions. One JSON Schema per tool serves all of them, under three different field names: input_schema for Anthropic, parameters for OpenAI, parametersJsonSchema for Gemini."
  },
  {
    "id": "82b3930",
    "date": "2026-08-31",
    "title": "Let departments act, behind an approval step",
    "detail": "Departments could only write replies. Operations can now create a project or a task, and every department can create a task, record a decision or a figure, and save a deliverable."
  },
  {
    "id": "320c7dd",
    "date": "2026-08-31",
    "title": "Stop company-wide memory and tasks being dropped by the cap",
    "detail": "Company-wide entries reached the filter and then fell off the end of it. Both blocks sorted everything together and sliced: decisions by date, so an important call from a year ago sat behind thirty newer department ones and never reached the prompt; figures by Map insertion order, so whether a company-wide one survived…"
  },
  {
    "id": "e5cbf90",
    "date": "2026-08-31",
    "title": "Let each department pick its own model, across three providers",
    "detail": "Departments all answered on one Anthropic model. They can now run on Anthropic, OpenAI, or Gemini independently, so a cheap model can take the bulk work and an expensive one can take the reasoning."
  },
  {
    "id": "820ccb4",
    "date": "2026-08-31",
    "title": "Lay messages out as a chat, and make the branding reach the icons",
    "detail": "The inbox drew left and right bubbles, which suits a phone and reads oddly on a desk. Messages now show the sender's picture and name once per run and indent the rest under it, the way a chat app does it."
  },
  {
    "id": "251bcaa",
    "date": "2026-08-31",
    "title": "Rewrite the wiki chapters in the voice the rest of the app now uses",
    "detail": "I wrote these two days ago with exactly the habits being stripped out everywhere else: rationale for design decisions nobody asked about, aphorisms in place of facts, and history of how the code got this way."
  },
  {
    "id": "8a4ca7e",
    "date": "2026-08-31",
    "title": "Strip Information and Admin, and rework the account menu",
    "detail": "Information explained caching for three sentences before showing the number, and Admin argued for its own design decisions in the middle of a page only an administrator can open. Both now state the fact and stop."
  },
  {
    "id": "d37d3fb",
    "date": "2026-08-31",
    "title": "Cut the copy back to what a user needs, and move setup into a profile menu",
    "detail": "Most of the writing in this app explained itself. Field hints that argued for the field, empty states that made a joke, a settings page that told an employee how the API key reaches the server. None of it is what someone opening the page wanted to know, and all of it was in the way."
  },
  {
    "id": "4ec017c",
    "date": "2026-08-31",
    "title": "Rebuild the palette on value structure, and finish the dashboard and wiki",
    "detail": "The dashboard drew every head as a card under \"Who you can ask\", which was the sidebar again in a second typeface. Gone; the panels take the full width in a two and three column grid and the counts collapse to one line."
  },
  {
    "id": "245d3fb",
    "date": "2026-08-31",
    "title": "Add tasks, and put the open ones in front of every head",
    "detail": "Deliverables are things produced: a reply worth keeping. There was no list of things not yet done, so \"what have we made\" was answerable and \"what is outstanding\" was not, and asking a head what to focus on got answered from nothing at all."
  },
  {
    "id": "2ae63cd",
    "date": "2026-08-31",
    "title": "Let each browser rearrange and prune the sidebar",
    "detail": "The drawer shipped one order for everyone: Work, Reference, Setup, Departments, Recent. Someone who lives in Projects and never opens Setup had no way to say so, and the sections nearest the bottom are the ones you scroll past twenty times a day."
  },
  {
    "id": "0dec428",
    "date": "2026-08-31",
    "title": "Rename the vague destinations, and replace the org chart with a dashboard",
    "detail": "Ruth was seeded as the Chief Executive Officer, which is the person using this app rather than the head answering them. She is now Chief of Staff: the same seniority, doing the work on the founder's behalf, with a prompt that says the call belongs to them. \"CEO Office\" in the nav becomes \"Chief of Staff\"."
  },
  {
    "id": "e5efb68",
    "date": "2026-08-31",
    "title": "Give the panel a memory: what the studio decided and measured",
    "detail": "Every conversation started from the same static Company Profile, so a head would contradict a decision made last month and had no figure to reason from. Nine freeform text boxes and fourteen tables, none of which held a fact."
  },
  {
    "id": "6a8fba6",
    "date": "2026-08-31",
    "title": "Stop the app claiming things are missing before it has loaded",
    "detail": "\"Department not found\" on every refresh was the app answering a question it could not yet answer. ChatView looked the department up and rendered the not-found panel when it came back empty, but empty is also what the store returns for the moment between knowing the workspace is hosted and having its contents."
  },
  {
    "id": "022a658",
    "date": "2026-08-31",
    "title": "Collapse the sidebar from the logo, and stop the stale flash on reload",
    "detail": "Clicking the workspace mark collapses the permanent drawer; clicking it again in the rail brings it back. Collapsing hides the drawer and lets the rail that medium and expanded windows already use take over at large too, so the two states are the drawer and the rail rather than a third narrow layout nobody maintains."
  },
  {
    "id": "fec7a14",
    "date": "2026-08-31",
    "title": "Give every department head its own colour",
    "detail": "departmentAccent hashed the department id into the six project accents. Nine heads cannot be given distinct colours by six, and the hash wasted one on top: Priya, Jun and Imani all came out cyan, Noor and Desmond violet, Ruth and Kai slate, and rose went to nobody."
  },
  {
    "id": "efe49a6",
    "date": "2026-08-31",
    "title": "Consolidate the skill library from 72 skills to 56",
    "detail": "Two sets of skills were written at different times and never checked against each other, so pairs of them covered the same ground twice: two on client contracts, two on mod licensing, three on choosing what to work on this month."
  },
  {
    "id": "9c913a5",
    "date": "2026-08-31",
    "title": "Stop every head closing by listing what it does not do",
    "detail": "Ask a head what it can do for you and it answered, then explained that pricing is Desmond and visuals are Noor. Nobody asked. It happened on every reply because three things pushed for it at once, and the worst was the last line of every department prompt: \"Out of scope: ...\" sitting where the model reads it last."
  },
  {
    "id": "472991a",
    "date": "2026-08-31",
    "title": "Colour code All Hands so eight replies can be told apart",
    "detail": "Every reply looked identical, so working out who was still writing meant reading eight names. Each department now has a stable colour derived from its id rather than stored, so nobody has to pick one and two people see the same mapping."
  },
  {
    "id": "bea2232",
    "date": "2026-08-31",
    "title": "Loosen the reply typography, and let tables lay out as tables",
    "detail": "Markdown already rendered; it was too tight to read. A reply is often several hundred words and the spacing was tuned for a short paragraph."
  },
  {
    "id": "f6962d4",
    "date": "2026-08-31",
    "title": "Fix a silent delete, an N+1, and status dots that meant nothing",
    "detail": "Deleting a conversation in a project shared with you removed nothing. The delete is scoped to the caller's address, so no row matched, while the client removed it optimistically: it vanished from the screen and came back on the next load."
  },
  {
    "id": "7b09781",
    "date": "2026-08-31",
    "title": "Collaborate in a shared project's conversations",
    "detail": "The project page shares to an approved address and takes it back, and says plainly that sharing gives someone the conversations filed there rather than the rest of the account. A project shared with you says who by, and that what you write is visible to everyone on it."
  },
  {
    "id": "2f63f7a",
    "date": "2026-08-31",
    "title": "Share projects across accounts, keeping one copy of each conversation",
    "detail": "A shared project's rows stay under its owner's address. Membership grants access to them rather than copying anything, which is the whole point when two people are writing into the same conversation: there is one canonical thread, not two that drift."
  },
  {
    "id": "9816850",
    "date": "2026-08-31",
    "title": "Fix sign out, which never worked",
    "detail": "The button posted a bare form to /api/auth/signout. next-auth requires a CSRF token in that request and rejects it without one, so the button did nothing at all, silently, on every account since auth was added. It fails worst on the machine where it matters most: a shared computer someone is trying to leave."
  },
  {
    "id": "6e2db55",
    "date": "2026-08-31",
    "title": "Group the navigation so it is five things, not eleven",
    "detail": "One flat list of eleven links was the thing that read as overwhelming, and adding Projects, Inbox and Admin to it made it worse each time."
  },
  {
    "id": "bf8f2b8",
    "date": "2026-08-31",
    "title": "Show what each skill costs, so turning one off is an informed choice",
    "detail": "Skills could already be disabled. What was missing was any way to see which ones were worth disabling: every enabled skill is injected in full on every message to that department, and a company-wide one is paid for across all of them."
  },
  {
    "id": "214fd12",
    "date": "2026-08-31",
    "title": "Make the panel yours: editable mark, sides, shortcut, plainer copy",
    "detail": "The mark is a component now, taking an uploaded logo or up to two letters, because HQ hardcoded into the sidebar is wrong for any business not called that. Navigation can sit on either edge, and the bare search key can be slash, k, or off; Ctrl and Cmd with K always work regardless."
  },
  {
    "id": "b0e8c10",
    "date": "2026-08-31",
    "title": "Give the heads more to work with about you and the business",
    "detail": "Four fields on the account, covering what you know, how you like answers, what you are working on now, and anything else. The first two are the difference between an answer pitched at a founder and one pitched at nobody; the third is what stops advice landing on last month's problem."
  },
  {
    "id": "0630b16",
    "date": "2026-08-31",
    "title": "Licence mods under LGPL so they can outlive the studio",
    "detail": "A mod that cannot be forked dies when the studio stops updating it. Every Minecraft version bump orphans mods whose authors moved on, and the ones that survive are the ones somebody else was allowed to pick up. Keeping the no-derivatives posture on this line would have been choosing that outcome."
  },
  {
    "id": "7bc2a50",
    "date": "2026-08-31",
    "title": "Licence the repository source-available, and give Legal the posture",
    "detail": "PolyForm Strict 1.0.0 verbatim, plus a separate Additional Grant. Strict grants everything except distributing the software or making changes and new works, which is the shape asked for, and it is attorney-drafted so it does not need defending the way a hand-written licence would."
  },
  {
    "id": "ea4ff1d",
    "date": "2026-08-31",
    "title": "Add the business handbook as skills, and fix horizontal safe-area padding",
    "detail": "Twenty-seven skills across all eight departments, biased toward the hard constraints and exact figures a model would otherwise invent plausibly and wrongly: Epic's royalty thresholds, Mojang's commercial usage rules, why plain GPL is incompatible with modding Minecraft, NeoForge namespace conventions, the PaperMC tunin…"
  },
  {
    "id": "2329b01",
    "date": "2026-08-31",
    "title": "Teach the coach from the founder's field guide",
    "detail": "Nine playbooks: delegation triage, reversible versus irreversible decisions at seventy per cent, feedback in both directions, sell before logistics, written and async, BATNA before negotiating, the traps new leaders fall into, the burnout loop, and the thresholds where the right answer changes."
  },
  {
    "id": "cb4f028",
    "date": "2026-08-31",
    "title": "Scope Library files to departments, and shorten the onboarding line",
    "detail": "A file now carries who can reach it: one department, every department, or nobody but you. Same shape as a skill's owner, so there is one idea to learn rather than two, and the field it uses already existed as a filter tag that nothing filtered by."
  },
  {
    "id": "fdffbd3",
    "date": "2026-08-31",
    "title": "Stop the line-length cap from pulling centred text off centre",
    "detail": "The cap was applied to every paragraph. A max-width narrows the box but leaves it left-aligned, so in a centred block the text centres inside a box that is itself off to one side: the department welcome had its name and description centred and its role title adrift, because only some of those elements were paragraphs."
  },
  {
    "id": "714cb20",
    "date": "2026-08-31",
    "title": "Fix headers sitting flush against the window, and add a private coach",
    "detail": "The padding complaint had one cause behind it. `.safe-top` set padding-top to the notch inset outright rather than adding to it, so a header written as `safe-top py-3` computed to zero top padding on any device without a notch."
  },
  {
    "id": "e867085",
    "date": "2026-08-31",
    "title": "Fix the settings gear, rename Messages to Inbox, add link previews",
    "detail": "The gear was a mangled edit of a line-art icon: stray V, H and V commands mid-path and large-arc flags that folded the teeth back across the body, so it drew as a tangle rather than a cog. Replaced with a correct path."
  },
  {
    "id": "75c29ae",
    "date": "2026-08-31",
    "title": "Stop publishing the allowlist on the sign-in page",
    "detail": "The sign-in page is public, and it printed the allowlist: with a single approved address it rendered that address in full, which was the case for the whole time only one account existed."
  },
  {
    "id": "13073e8",
    "date": "2026-08-31",
    "title": "Add an onboarding page to send people on their first day",
    "detail": "One page rather than a wizard, because it is meant to be linked, skimmed, and come back to. It reads the workspace rather than hardcoding it, so it names the actual heads and their count and stays right when either changes."
  },
  {
    "id": "6064962",
    "date": "2026-08-31",
    "title": "Say which server has no key",
    "detail": "The same message answered for the development server and the deployment, which reads as a bug when you know you set the key: it is on Vercel, and Vercel's environment does not reach localhost. Each now names the server it came from and the fix that applies there."
  },
  {
    "id": "a792cd0",
    "date": "2026-08-31",
    "title": "Let an administrator review conversations across accounts",
    "detail": "Scoped to conversations with department heads, which are work on a company tool. Direct messages between people are deliberately excluded: reading one is a different decision and should be made on its own, not inherited from an unrelated feature."
  },
  {
    "id": "fa6e5ec",
    "date": "2026-08-31",
    "title": "Give every screen the same measure, and fix the avatar outline",
    "detail": "The All Hands avatars were wrapped in a span carrying rounded-full and a shadow. A span is display:inline, so it never took the shape of the circle inside it and the shadow drew on a tall, mis-sized box beside the picture. The avatar takes its own title and shadow now, and the wrappers are gone."
  },
  {
    "id": "6be0012",
    "date": "2026-08-31",
    "title": "Cut a line of noise from every head, and let lists settle in",
    "detail": "Presence moved onto the avatar as a corner dot, which is where every app that shows presence puts it and which removes a whole metadata line from each org chart row. What is left reads as name, role, and a count, rather than three competing lines of small text."
  },
  {
    "id": "2e65f54",
    "date": "2026-08-31",
    "title": "Replace department emoji with editable pictures",
    "detail": "Each head now carries an uploaded picture, cropped to a centred square at 256px so the row stays small, and falls back to their initial on a tinted disc rather than a glyph. The picture is set from the department editor in Settings."
  },
  {
    "id": "93d983b",
    "date": "2026-08-31",
    "title": "Stop tracking the throwaway build directory",
    "detail": "A dev server run with NEXT_DIST_DIR set to .next-noauth, to check how the app behaves without auth configured, left 233 build artefacts that the previous commit swept in. .gitignore listed each dist directory by name, which only ever covers the ones already thought of, so it now ignores the pattern instead."
  },
  {
    "id": "346718f",
    "date": "2026-08-31",
    "title": "Fix messages vanishing on send, and add Messages",
    "detail": "The bug first. send() creates a conversation and immediately saves a message into it. Both functions come from the same useStore() value, so the second one closed over a conversation list built before the first had run, missed its lookup, and returned without writing."
  },
  {
    "id": "57bcc29",
    "date": "2026-08-31",
    "title": "Say when the server holds the key instead of showing an empty field",
    "detail": "The key lives in localStorage so it never reaches Postgres, which is the right call and also why it does not follow you to a phone. On a device that has never been told, the field simply looked blank and broken."
  },
  {
    "id": "3c642d7",
    "date": "2026-08-30",
    "title": "Measure what a workspace snapshot actually weighs",
    "detail": "loadWorkspace maps every file row through toAttachment, which carries the base64 data column, and rehydrates message attachments the same way. Eight one-megabyte screenshots make an 11.2MB JSON response, sent on every page load, to render a Library that only shows thumbnails and names until one is opened."
  },
  {
    "id": "d4a3902",
    "date": "2026-08-30",
    "title": "Stop rebuilding the store on every render, and shrink the way in",
    "detail": "Two measured problems, both found by testing rather than reading."
  },
  {
    "id": "1a60dfa",
    "date": "2026-08-30",
    "title": "Harden the deployment without touching the way in",
    "detail": "Five things, none of which change how signing in works."
  },
  {
    "id": "9ca031d",
    "date": "2026-08-30",
    "title": "Add projects, which group work across the org chart",
    "detail": "Departments own the heads. A launch does not: it pulls in engineering, design, and marketing at once, and until now the only way to see it whole was to remember which head you asked what."
  },
  {
    "id": "14880f9",
    "date": "2026-08-30",
    "title": "Give the API key somewhere to live",
    "detail": "Keeping the key out of Postgres was the right call. Leaving it with nowhere else to go was not: the store forced apiKey to \"\" in hosted mode and stripped it from every write, so on the deployment the field took input, discarded it, and read back empty. The workspace id had the same hole."
  },
  {
    "id": "cd24e5d",
    "date": "2026-08-30",
    "title": "Stop treating signed in and hosted as the same fact",
    "detail": "The status route answered hosted:false, signedIn:false whenever the database was unconfigured, even for someone who had just completed the Google flow. The Account page reads that answer, so it told a signed in user they were not signed in."
  },
  {
    "id": "c221e1f",
    "date": "2026-08-30",
    "title": "Look the workspace id up instead of sending the user to hunt for it",
    "detail": "An identity-linked key that spans several workspaces refuses every Messages request until one is named, and the id is otherwise buried in the Console."
  },
  {
    "id": "e00f760",
    "date": "2026-08-31",
    "title": "Add Vercel Speed Insights to project",
    "detail": "## Vercel Speed Insights Installation"
  },
  {
    "id": "b4e0e49",
    "date": "2026-08-30",
    "title": "Add an Account page, and support identity-linked API keys",
    "detail": "Account is who is using the app, as distinct from the Company Profile, which describes the business. Name, role, pronouns, and timezone, backed by a table in both storages and populated from Google on sign in."
  },
  {
    "id": "ec7a73c",
    "date": "2026-08-31",
    "title": "Install Vercel Web Analytics",
    "detail": "## Vercel Web Analytics Installation"
  },
  {
    "id": "5085df3",
    "date": "2026-08-30",
    "title": "Fix a cascade the client did and the server did not, add a database smoke test",
    "detail": "Deleting a head removed its conversations in the browser and in IndexedDB, but left them behind in Postgres, pointing at a department that no longer existed. The server now removes the conversations and their messages in the same transaction."
  },
  {
    "id": "a83f153",
    "date": "2026-08-30",
    "title": "Swap the store between local and hosted storage",
    "detail": "useStore() keeps exactly the same interface, so no page changed. The provider asks /api/workspace/status which storage it is on, then either keeps the live Dexie queries or holds a server snapshot in state."
  },
  {
    "id": "b0775cf",
    "date": "2026-08-30",
    "title": "Add the hosted workspace schema and data layer",
    "detail": "Ten Postgres tables via Drizzle, every row scoped by the signed-in email. There is no users table: auth is JWT only with a Google allowlist, so the email is the whole identity and a table mapping it to itself would earn nothing."
  },
  {
    "id": "147196f",
    "date": "2026-08-30",
    "title": "Add Google sign in with an email allowlist, and hold the key server side",
    "detail": "Auth turns itself on only when AUTH_SECRET, AUTH_GOOGLE_ID and AUTH_GOOGLE_SECRET are all present, so a local checkout runs exactly as before without an OAuth client. Once configured, every route is behind the proxy and anyone Google authenticates who is not on ALLOWED_EMAILS is refused."
  },
  {
    "id": "e72dd11",
    "date": "2026-08-30",
    "title": "Library and Information, with PDFs and Word files readable by the heads",
    "detail": "Files, deliverables, and skills are all things the studio keeps, so they share one destination and one tab bar. /skills and /deliverables redirect."
  },
  {
    "id": "8db1bea",
    "date": "2026-08-30",
    "title": "Company wide skills and a global search palette",
    "detail": "Skills can now be owned by the whole company rather than one department. A company skill is injected into every head's prompt, so it costs its tokens eight times over; the editor says so where the owner is chosen. Two shipped: Handoff Note and Decision Record, both cross cutting by nature."
  },
  {
    "id": "f6ec389",
    "date": "2026-08-30",
    "title": "Stop billing on disconnect, add image attachments and CI",
    "detail": "The chat route never read request.signal, so pressing Stop or closing the tab aborted the browser fetch while the model kept generating and billing. It now tears down the upstream stream on disconnect and on stream cancel."
  },
  {
    "id": "dc55329",
    "date": "2026-08-30",
    "title": "Eterneon: AI operating system for the studio",
    "detail": "A CEO orchestrator over seven department heads, each with its own persona, scoped system prompt, SKILL.md playbooks, and separate conversation history."
  }
];

/** What the newest entry is, for deciding whether somebody has seen it. */
export const LATEST = "1fef674";
