/**
 * Every heading in the manual, and the chapter it sits under.
 *
 * Generated by `npm run documentation-titles`. Do not edit: documentation.ts
 * is the source, and documentation-test fails when this stops matching it.
 *
 * It exists so the command palette can search the manual without the shell
 * carrying it. See scripts/documentation-titles.ts for why that matters.
 */

export interface DocHeading {
  /** The anchor on /documentation. */
  id: string;
  title: string;
  chapter: string;
}

export const DOC_HEADINGS: DocHeading[] = [
  {
    "id": "what-this-is",
    "title": "Overview",
    "chapter": "Getting started"
  },
  {
    "id": "first-ten-minutes",
    "title": "Setup",
    "chapter": "Getting started"
  },
  {
    "id": "connecting-a-model",
    "title": "Models and keys",
    "chapter": "Getting started"
  },
  {
    "id": "conversations",
    "title": "Conversations",
    "chapter": "Daily use"
  },
  {
    "id": "tasks-projects",
    "title": "Tasks and projects",
    "chapter": "Daily use"
  },
  {
    "id": "library",
    "title": "Library",
    "chapter": "Daily use"
  },
  {
    "id": "skills",
    "title": "Skills",
    "chapter": "Daily use"
  },
  {
    "id": "memory",
    "title": "Memory",
    "chapter": "Daily use"
  },
  {
    "id": "meetings",
    "title": "Meetings",
    "chapter": "Working together"
  },
  {
    "id": "inbox",
    "title": "Inbox",
    "chapter": "Working together"
  },
  {
    "id": "schedules",
    "title": "Schedules",
    "chapter": "Working together"
  },
  {
    "id": "people",
    "title": "People and roles",
    "chapter": "Working together"
  },
  {
    "id": "web-search",
    "title": "Web search",
    "chapter": "Extensions"
  },
  {
    "id": "integrations",
    "title": "Integrations",
    "chapter": "Extensions"
  },
  {
    "id": "wiki",
    "title": "Wiki",
    "chapter": "Extensions"
  },
  {
    "id": "settings",
    "title": "Settings",
    "chapter": "Administration"
  },
  {
    "id": "backups",
    "title": "Backups",
    "chapter": "Administration"
  },
  {
    "id": "privacy",
    "title": "Privacy",
    "chapter": "Administration"
  },
  {
    "id": "costs",
    "title": "Costs",
    "chapter": "Administration"
  },
  {
    "id": "troubleshooting",
    "title": "Troubleshooting",
    "chapter": "Administration"
  }
];
