import { promptFingerprint } from "./coachSkills";
import type { Skill } from "./types";
import type { MutationOp } from "./workspace";

/**
 * Fingerprints of every skill body this app has shipped, across all versions.
 *
 * Consolidating the library means rewriting some skills and retiring others,
 * and both have to reach a workspace that already has the old ones. A stored
 * skill matching one of these has never been edited, so replacing or removing
 * it is safe. Anything else is the owner's own writing and is left alone.
 *
 * Generated by scripts/shipped-skills.ts; do not edit by hand.
 */
/*
 * Bodies that shipped before, and are still sitting in real workspaces.
 *
 * Reconciliation rewrites a skill only when its current fingerprint is in this
 * set, which is how it tells a copy nobody has touched from one somebody has
 * rewritten. The generator writes what ships today and nothing else, on the
 * reasoning that nothing out there holds an older copy. That was true when it
 * was written and stopped being true the moment there were customers.
 *
 * Editing a shipped skill and regenerating therefore drops the fingerprint of
 * the body every existing workspace is holding, so those copies stop being
 * recognised and the improvement never reaches the people it was written for.
 * Silently: the test passes, the deploy is clean, and nothing changes.
 *
 * So a previous body is added here by hand when a shipped skill changes.
 * `npx tsx scripts/old-fingerprints.ts <old file>` prints them.
 */
const PREVIOUSLY_SHIPPED = [
  // Pricing Model, before the floor covered landed cost and card fees.
  "11qhaue",
  // Monthly Books Check, before cash and earned income were told apart.
  "1a1qc1c",
  // Privacy and Compliance Check, before it covered platform terms and
  // computer misuse law alongside data protection.
  "1qtgled",
];

export const SHIPPED_SKILL_BODIES = new Set([
  ...PREVIOUSLY_SHIPPED,
  "11d9u46",
  "1733mae",
  "1g2hd6f",
  "1joxl23",
  "1p18gbz",
  "1s469c3",
  "1vybfh7",
  "1wvk645",
  "1xs0ut8",
  "7clg1x",
  "bb6cz8",
  "btesfu",
  "c9s8em",
  "dgzk03",
  "dyeax5",
  "ekn391",
  "fasese",
  "gd63ro",
  "kxfq4t",
  "nk6nvf",
  "ou1a86",
  "pi48w9",
  "u7uqj5",
  "vi7mm1",
  "wnle6q",
  "yksfjl",
  "zb6lv1",
]);

/**
 * Skills removed from a workspace that still has them.
 *
 * Empty, and that is the normal state. It fills only when a shipped skill is
 * withdrawn and should be taken out of workspaces that already received it,
 * and empties again once every workspace has been through a load. Removing a
 * skill from the shipped set is not enough on its own: reconciliation leaves
 * anything it is not told to delete, which is what keeps a workspace's own
 * writing safe.
 */
export const RETIRED_SKILL_IDS: [id: string, mergedInto: string][] = [];

/**
 * Works out what to change in a workspace's skills to bring it up to date.
 *
 * Kept apart from the store so it can be tested without a browser, since it
 * deletes and overwrites rows in a live workspace and getting it wrong loses
 * someone's writing.
 *
 * `shipped` is everything this app currently ships, and is only ever used to
 * update a skill the workspace already has. `additions` is the subset new
 * enough that the workspace cannot have seen it, so a missing one means never
 * delivered rather than deleted. Nothing records which skills a workspace has
 * been offered, so that distinction has to be made by the caller; passing the
 * whole library as `additions` would resurrect every skill anyone deleted.
 *
 * An update or a delete applies only where the stored body still fingerprints
 * to something this app shipped. Anything else has been edited, and is left
 * untouched permanently.
 */
export function skillReconciliation(
  stored: Skill[],
  shipped: Skill[],
  additions: Skill[],
  now: number = Date.now(),
  /** Injectable so the rule can be tested with nothing actually withdrawn. */
  withdrawn: [id: string, mergedInto: string][] = RETIRED_SKILL_IDS,
): MutationOp[] {
  const owned = new Map(stored.map((s) => [s.id, s]));
  const untouched = (s: Skill) => SHIPPED_SKILL_BODIES.has(promptFingerprint(s.content));
  const ops: MutationOp[] = [];

  const rewritten = shipped.flatMap((fresh) => {
    const mine = owned.get(fresh.id);
    if (!mine) return [];
    if (mine.content === fresh.content && mine.description === fresh.description) return [];
    if (!untouched(mine)) return [];
    return [
      {
        ...mine,
        name: fresh.name,
        description: fresh.description,
        content: fresh.content,
        updatedAt: now,
      },
    ];
  });

  const added = additions.filter((s) => !owned.has(s.id));
  if (rewritten.length || added.length) {
    ops.push({ table: "skills", action: "upsert", rows: [...added, ...rewritten] });
  }

  const retired = withdrawn.flatMap(([id]) => {
    const mine = owned.get(id);
    return mine && untouched(mine) ? [id] : [];
  });
  if (retired.length) ops.push({ table: "skills", action: "delete", ids: retired });

  return ops;
}
