import { promptFingerprint } from "./coachSkills";
import type { Skill } from "./types";
import type { MutationOp } from "./workspace";

/**
 * Fingerprints of every skill body this app has shipped, across all versions.
 *
 * Consolidating the library means rewriting some skills and retiring others,
 * and both have to reach a workspace that already has the old ones. A stored
 * skill matching one of these has never been edited, so replacing or removing
 * it is safe. Anything else is the owner's own writing and is left alone.
 *
 * Generated by scripts/shipped-skills.ts; do not edit by hand.
 */
export const SHIPPED_SKILL_BODIES = new Set([
  "103imrv",
  "134s2mi",
  "138d8ii",
  "13e4uu2",
  "15ubgg2",
  "1684ro2",
  "1733mae",
  "18fdz6w",
  "18r6zsb",
  "1905qhd",
  "1amwvx7",
  "1bka95m",
  "1bntfxe",
  "1c412r0",
  "1codm3v",
  "1dinfx8",
  "1fxm1l4",
  "1g2hd6f",
  "1g8nl5m",
  "1h6bohd",
  "1hb1ndq",
  "1hlebq",
  "1hv45sj",
  "1hz1b8q",
  "1iea0lu",
  "1k36yb2",
  "1kp6m0q",
  "1ksa5wc",
  "1l1j4z5",
  "1lw4pn9",
  "1mi3qhi",
  "1mqqk45",
  "1nzbgtv",
  "1og0n1g",
  "1p4duxg",
  "1s840no",
  "1sq0w5o",
  "1t20083",
  "1tejtfb",
  "1vns4nu",
  "1vxq5y1",
  "1vybfh7",
  "1wh385",
  "1wvnywx",
  "1y9c1ao",
  "48hh9r",
  "4s6x97",
  "5h7rcc",
  "5uccgz",
  "8mrrah",
  "8sypkr",
  "a9r3qd",
  "anv49y",
  "b9r5ws",
  "btesfu",
  "cm6x02",
  "cqdnvi",
  "dewjsg",
  "dsqhmu",
  "dy93n9",
  "etna78",
  "fasese",
  "fj2zjt",
  "gd63ro",
  "genzxk",
  "j583zr",
  "jnax2n",
  "kxfq4t",
  "ln5o12",
  "lx5krn",
  "mf0xq3",
  "mm48bk",
  "ofxajn",
  "omiisp",
  "p1mk1t",
  "pi48w9",
  "sbhzhy",
  "tg8xah",
  "tgwvjb",
  "tt6mew",
  "u268d5",
  "uqxdvg",
  "v8ysrn",
  "vi7mm1",
  "wvn82u",
  "xz7zty",
  "z0qxza",
  "z2iaxv",
]);

/**
 * Skills that were folded into another one.
 *
 * The library grew to seventy-two by adding a second set alongside the first
 * without checking them against each other, so several pairs covered the same
 * ground twice: two on client contracts, two on mod licensing, three on
 * choosing what matters this month. Their content now lives in the skill named
 * beside each id, which is the skill they were folded into.
 *
 * Removed from a workspace only where the stored copy still matches what this
 * app shipped, so an edited one is never deleted.
 */
export const RETIRED_SKILL_IDS: [id: string, mergedInto: string][] = [
  ["skill_hb_ceo_which-one-this-month", "Weekly Priority Call"],
  ["skill_seed_ceo_ship-cut-or-defer", "Weekly Priority Call"],
  ["skill_hb_marketing_wishlists-before-next-fest", "Steam Page Copy"],
  ["skill_hb_marketing_mod-listing-discovery", "Mod Listing Copy"],
  ["skill_hb_marketing_ask-for-the-referral", "Website Client Pitch"],
  ["skill_hb_social_devlog-cadence", "Devlog Post"],
  ["skill_seed_social_short-form-script", "Devlog Post"],
  ["skill_hb_social_when-social-is-not-the-channel", "Weekly Content Calendar"],
  ["skill_hb_design_game-hud-decisions", "Game UI Review"],
  ["skill_hb_finance_quoting-client-web-work", "Website Quote"],
  ["skill_hb_finance_ue5-royalty-arithmetic", "Game Revenue Forecast"],
  ["skill_hb_legal_mod-licence-compatibility", "Mod and Asset Licensing"],
  ["skill_hb_legal_client-contract-clauses", "Client Web Agreement"],
  ["skill_hb_operations_scope-discipline-on-client-work", "Client Onboarding"],
  ["skill_hb_engineering_ue5-performance-method", "Simulation Performance"],
  ["skill_hb_engineering_neoforge-conventions", "Mod Architecture"],
];

/**
 * Works out what to change in a workspace's skills to bring it up to date.
 *
 * Kept apart from the store so it can be tested without a browser, since it
 * deletes and overwrites rows in a live workspace and getting it wrong loses
 * someone's writing.
 *
 * `shipped` is everything this app currently ships, and is only ever used to
 * update a skill the workspace already has. `additions` is the subset new
 * enough that the workspace cannot have seen it, so a missing one means never
 * delivered rather than deleted. Nothing records which skills a workspace has
 * been offered, so that distinction has to be made by the caller; passing the
 * whole library as `additions` would resurrect every skill anyone deleted.
 *
 * An update or a delete applies only where the stored body still fingerprints
 * to something this app shipped. Anything else has been edited, and is left
 * untouched permanently.
 */
export function skillReconciliation(
  stored: Skill[],
  shipped: Skill[],
  additions: Skill[],
  now: number = Date.now(),
): MutationOp[] {
  const owned = new Map(stored.map((s) => [s.id, s]));
  const untouched = (s: Skill) => SHIPPED_SKILL_BODIES.has(promptFingerprint(s.content));
  const ops: MutationOp[] = [];

  const rewritten = shipped.flatMap((fresh) => {
    const mine = owned.get(fresh.id);
    if (!mine) return [];
    if (mine.content === fresh.content && mine.description === fresh.description) return [];
    if (!untouched(mine)) return [];
    return [
      {
        ...mine,
        name: fresh.name,
        description: fresh.description,
        content: fresh.content,
        updatedAt: now,
      },
    ];
  });

  const added = additions.filter((s) => !owned.has(s.id));
  if (rewritten.length || added.length) {
    ops.push({ table: "skills", action: "upsert", rows: [...added, ...rewritten] });
  }

  const retired = RETIRED_SKILL_IDS.flatMap(([id]) => {
    const mine = owned.get(id);
    return mine && untouched(mine) ? [id] : [];
  });
  if (retired.length) ops.push({ table: "skills", action: "delete", ids: retired });

  return ops;
}
