/**
 * Turns the commit history into the Changelog people read in the panel.
 *
 * Generated rather than hand kept, because a hand kept one goes stale the first
 * week somebody is busy. The commit subjects in this repository are already
 * written as plain sentences about what changed, which is the only reason this
 * works; a repository full of "fix bug" would need release notes written by
 * hand.
 *
 * Committed as a file rather than read at runtime. Vercel builds from a shallow
 * clone and the running app has no git at all, so the history has to be baked
 * in while it is still available.
 *
 * Run with: npm run changelog
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

/** Separates fields inside a line, and entries from each other. */
const FIELD = "";
const ENTRY = "";

/**
 * Commits nobody outside this repository benefits from reading.
 *
 * A changelog is for the people using the panel. Formatting passes, comment
 * edits, and tooling changes are real work and are not news, and a list padded
 * with them is one people stop opening.
 */
const NOISE =
  /^(chore|docs|style|refactor|test|ci|build|bump|merge|wip|typo|lint|format|comment)\b/i;

const SKIP_TRAILER = /^(co-authored-by|signed-off-by|🤖|generated with)/i;

interface Entry {
  id: string;
  date: string;
  title: string;
  detail: string;
}

function history(): Entry[] {
  const raw = execFileSync(
    "git",
    ["log", `--pretty=format:%h${FIELD}%ad${FIELD}%s${FIELD}%b${ENTRY}`, "--date=short"],
    { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
  );

  const entries: Entry[] = [];
  for (const chunk of raw.split(ENTRY)) {
    const line = chunk.trim();
    if (!line) continue;
    const [id, date, title, body = ""] = line.split(FIELD);
    if (!id || !date || !title) continue;
    if (NOISE.test(title)) continue;

    entries.push({ id, date, title: title.trim(), detail: summarise(body) });
  }
  return entries;
}

/**
 * The first paragraph of the message, which is where the commits here say what
 * changed. Everything after it is reasoning for whoever reads the diff.
 */
function summarise(body: string): string {
  const paragraphs = body
    .split(/\n\s*\n/)
    .map((p) =>
      p
        .split("\n")
        .map((l) => l.trim())
        .filter((l) => l && !SKIP_TRAILER.test(l))
        .join(" ")
        .trim(),
    )
    .filter(Boolean);

  const first = paragraphs[0] ?? "";
  if (first.length <= 320) return first;
  // Cut at a sentence rather than mid word, so it reads as an end.
  const cut = first.slice(0, 320);
  const stop = Math.max(cut.lastIndexOf(". "), cut.lastIndexOf("? "));
  return stop > 120 ? cut.slice(0, stop + 1) : `${cut.trimEnd()}…`;
}

const entries = history();

const file = `// Generated by scripts/changelog.ts. Run \`npm run changelog\` after a release.
// Edit the commit messages, not this file.

export interface ChangelogEntry {
  /** The short commit hash, which is also a stable key for the list. */
  id: string;
  /** ISO date, so entries group by day without parsing anything. */
  date: string;
  title: string;
  /** The first paragraph of the commit message, or empty. */
  detail: string;
}

/** Newest first, which is the order the screen shows them in. */
export const CHANGELOG: ChangelogEntry[] = ${JSON.stringify(entries, null, 2)};

/** What the newest entry is, for deciding whether somebody has seen it. */
export const LATEST = ${JSON.stringify(entries[0]?.id ?? "")};
`;

writeFileSync("src/lib/changelog.data.ts", file);
console.log(`wrote ${entries.length} entries to src/lib/changelog.data.ts`);
console.log(`newest: ${entries[0]?.date} ${entries[0]?.title}`);
