/**
 * Writes the list of changelog ids, so the shell does not carry the changelog.
 *
 * ProfileMenu shows a dot for entries somebody has not read, and it sits in the
 * shell on every screen. It reached that count through changelogSeen, which
 * imported CHANGELOG to find the index of the last id somebody saw. Finding an
 * index needs the ids in order and nothing else, but importing them pulled in
 * every word of every entry: 316KB of source, in the chunk every visitor
 * downloads on every page, to draw a dot.
 *
 * So the ids live apart, generated from the data rather than typed twice.
 * changelog-test asserts the two agree, which is what stops this becoming a
 * list that silently stops matching.
 *
 *   npm run changelog-ids
 */
import { writeFileSync } from "node:fs";
import { CHANGELOG, LATEST } from "../src/lib/changelog.data";

const ids = CHANGELOG.map((entry) => entry.id);

const file = `/**
 * Every changelog entry id, newest first, and the newest of them.
 *
 * Generated by \`npm run changelog-ids\`. Do not edit by hand.
 *
 * This exists so the account menu can count what somebody has not read without
 * the shell carrying the changelog itself. The prose is 316KB of source and is
 * needed only by the page that renders it; the dot needs an ordered list of
 * ids. changelog-test asserts the two still agree.
 */
export const CHANGELOG_IDS: string[] = [
${ids.map((id) => `  "${id}",`).join("\n")}
];

/** The newest entry, which is what "seen everything" is marked as. */
export const LATEST = "${LATEST}";
`;

writeFileSync("src/lib/changelog.ids.ts", file);
console.log(`${ids.length} ids written, latest ${LATEST}`);
