/**
 * Writes the list of documentation headings, so the shell does not carry the manual.
 *
 * The command palette lives in the shell, on every screen, and searching the
 * documentation from it needs the headings and nothing else. Importing them
 * from documentation.ts would have pulled every word of the manual with them:
 * 24KB of source in the chunk every visitor downloads on every page, to match
 * two dozen short strings.
 *
 * The same reasoning as changelog.ids, and the same arrangement: generated
 * rather than typed twice, with a test that fails when the two disagree.
 *
 *   npm run documentation-titles
 */
import { writeFileSync } from "node:fs";
import { DOCUMENTATION } from "../src/lib/documentation";

const rows = DOCUMENTATION.flatMap((chapter) =>
  chapter.sections.map((section) => ({
    id: section.id,
    title: section.title,
    chapter: chapter.title,
  })),
);

const file = `/**
 * Every heading in the manual, and the chapter it sits under.
 *
 * Generated by \`npm run documentation-titles\`. Do not edit: documentation.ts
 * is the source, and documentation-test fails when this stops matching it.
 *
 * It exists so the command palette can search the manual without the shell
 * carrying it. See scripts/documentation-titles.ts for why that matters.
 */

export interface DocHeading {
  /** The anchor on /documentation. */
  id: string;
  title: string;
  chapter: string;
}

export const DOC_HEADINGS: DocHeading[] = ${JSON.stringify(rows, null, 2)};
`;

writeFileSync("src/lib/documentation.titles.ts", file);
console.log(`wrote ${rows.length} headings`);
