var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/workspace/status/route.js")
R.c("server/chunks/node_modules_next_0nbfm-5._.js")
R.c("server/chunks/node_modules_@auth_core_11waxm4._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_0qgh5y5._.js")
R.c("server/chunks/node_modules_drizzle-orm_0kui1js._.js")
R.c("server/chunks/node_modules_0t81o4u._.js")
R.c("server/chunks/[root-of-the-server]__104820-._.js")
R.c("server/chunks/_next-internal_server_app_api_workspace_status_route_actions_1vos2i9.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/workspace/status/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/workspace/status/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
